apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
spec:
  selector:
    matchLabels:
      app: quiz-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
        - name: quiz-backend
          image: ervisa/backend-new:7
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: quiz-backend
  type: ClusterIP
status:
  loadBalancer: {}
